services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lunaris
    restart: always
    stdin_open: true
    tty: true
    command: python main.py
    environment:
      - PYTHONPATH=/app