services:
# -----------------------------------------------------
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data 
    networks:
    - lunaris-internal-network
# -----------------------------------------------------
  simulator:
    build: ./simulators
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=mosquitto
    restart: on-failure
    networks:
      - lunaris-internal-network
# -----------------------------------------------------
  influxdb:
    image: influxdb:2.7
    ports:
    - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PSWD}
      - DOCKER_INFLUXDB_INIT_ORG=project
      - DOCKER_INFLUXDB_INIT_BUCKET=lunaris
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - lunaris-internal-network
# -----------------------------------------------------
  ingestion:
    build: ./ingestion
    depends_on:
      - mosquitto
      - influxdb
    environment:
      - MQTT_BROKER=mosquitto
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=project
      - INFLUX_BUCKET=lunaris
    restart: on-failure
    networks:
      - lunaris-internal-network
# -----------------------------------------------------
  api:
    build: ./api
    depends_on:
      - influxdb
    ports:
      - "5000:5000"
    environment:
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=mi-token-secreto
      - INFLUX_ORG=esei
      - INFLUX_BUCKET=iot_data
    networks:
      - lunaris-internal-network
      
volumes:
  influxdb_data:
networks:
  lunaris-internal-network:
    name: lunaris-internal-network 